list = ["Acronym",
"Anime",
"Apps",
"Asq",
"Astronomy",
"Bard AI",
"Carbon",
"CC Generator",
"Chat GPT",
"Chatbot AI",
"Code Executor",
"Currency",
"Dictionary Search",
"Figlet Generator",
"Github Search",
"Global News",
"Google Search",
"Grammarly",
"Image Generator",
"Image Search",
"IMDb Search",
"Info Checker",
"Info Generator",
"LLama 2",
"Logo Maker",
"Lyrics Search",
"Morse Code",
"Note Writer",
"Npm Search",
"NSFW Detector",
"OCR Scanner",
"Paraphraser",
"Pasting Bin",
"Proxy Finder",
"PyPi Search",
"QR Code Gen",
"Quotly Sticker",
"Random Fun",
"Rayso Maker",
"Reddit Search",
"Remove BG",
"Short Links Tool",
"SK Checker",
"Song Finder",
"Spam Detector",
"Spell Checker",
"Spotify Search",
"Stackoverflow Search",
"Sticker Search",
"Telegraph",
"TMDb Search",
"Torrent Search",
"Translator",
"Truth or Dare",
"Ubuntu Search",
"Udemy Course",
"Unsplash Search",
"Urban Search",
"Wallpaper Search",
"Weather Search",
"Webshot Taker",
"Wikipedia Search",
"Xda Devs Search",
"YouTube Search"]

import os

for i in list:

    os.mkdir(i.replace(" ","-"))
    with open(f"{i.replace(" ","-")}/index.mdx", "w") as f:
        f.write(f"""---
title: {i}
description: Function {i} of class SafoneAPI() in
---
""")
